export const actionTypes = {
  STORY_UNDO_DELETE_REQUEST: "STORY_UNDO_DELETE_REQUEST",
  STORY_UNDO_DELETE_SUCCESS: "STORY_UNDO_DELETE_SUCCESS",
  STORY_UNDO_DELETE_FAIL: "STORY_UNDO_DELETE_FAIL",

  STORY_LIST_REQUEST: "STORY_LIST_REQUEST",
  STORY_LIST_SUCCESS: "STORY_LIST_SUCCESS",
  STORY_LIST_FAIL: "STORY_LIST_FAIL",

  STORY_PRIVATE_REQUEST: "STORY_PRIVATE_REQUEST",
  STORY_PRIVATE_SUCCESS: "STORY_PRIVATE_SUCCESS",
  STORY_PRIVATE_FAIL: "STORY_PRIVATE_FAIL",

  STORY_DETAILS_REQUEST: "STORY_DETAILS_REQUEST",
  STORY_DETAILS_SUCCESS: "STORY_DETAILS_SUCCESS",
  STORY_DETAILS_FAIL: "STORY_DETAILS_FAIL",

  STORY_COMMENT_REQUEST: "STORY_COMMENT_REQUEST",
  STORY_COMMENT_SUCCESS: "STORY_COMMENT_SUCCESS",
  STORY_COMMENT_FAIL: "STORY_COMMENT_FAIL",

  STORY_LIKE_REQUEST: "STORY_LIKE_REQUEST",
  STORY_LIKE_SUCCESS: "STORY_LIKE_SUCCESS",
  STORY_LIKE_FAIL: "STORY_LIKE_FAIL",

  STORY_UNLIKE_REQUEST: "STORY_UNLIKE_REQUEST",
  STORY_UNLIKE_SUCCESS: "STORY_UNLIKE_SUCCESS",
  STORY_UNLIKE_FAIL: "STORY_UNLIKE_FAIL",

  STORY_ADD_REQUEST: "STORY_ADD_REQUEST",
  STORY_ADD_SUCCESS: "STORY_ADD_SUCCESS",
  STORY_ADD_FAIL: "STORY_ADD_FAIL",

  STORY_UPDATE_REQUEST: "STORY_UPDATE_REQUEST",
  STORY_UPDATE_SUCCESS: "STORY_UPDATE_SUCCESS",
  STORY_UPDATE_FAIL: "STORY_UPDATE_FAIL",

  STORY_DELETE_REQUEST: "STORY_DELETE_REQUEST",
  STORY_DELETE_SUCCESS: "STORY_DELETE_SUCCESS",
  STORY_DELETE_FAIL: "STORY_DELETE_FAIL",

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAIL: "USER_UPDATE_FAIL",

  USER_PROFILE_DELETE_REQUEST: "USER_PROFILE_DELETE_REQUEST",
  USER_PROFILE_DELETE_SUCCESS: "USER_PROFILE_DELETE_SUCCESS",
  USER_PROFILE_DELETE_FAIL: "USER_PROFILE_DELETE_FAIL",

  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAIL: "USER_PROFILE_FAIL",

  USER_LOGOUT: "USER_LOGOUT",

  USERS_LIST_REQUEST: "USERS_LIST_REQUEST",
  USERS_LIST_SUCCESS: "USERS_LIST_SUCCESS",
  USERS_LIST_FAIL: "USERS_LIST_FAIL",
};
